/**
 * CSS Generator for Event-Specific Styling (Plan 003)
 *
 * Converts EventStyleConfig (from Python scraping layer) into CSS custom properties
 * that can be injected into generated HTML pages for dynamic event-specific styling.
 */

import type { EventStyleConfig } from './types/index.js';

/**
 * Generates CSS custom properties from an EventStyleConfig
 *
 * @param config - The event style configuration from Python scraping
 * @returns CSS string with custom properties in :root selector
 */
export function generateEventCSS(config: EventStyleConfig): string {
  const lines: string[] = [];

  // Add header comment with event metadata
  lines.push('/*');
  lines.push(` * Event-Specific Styles (Generated by Plan 003)`);
  lines.push(` * Event: ${config.eventName}`);
  lines.push(` * Event ID: ${config.eventId}`);
  lines.push(` * Source: ${config.sourceUrl}`);
  if (config.scrapedAt) {
    lines.push(` * Scraped: ${config.scrapedAt}`);
  }
  lines.push(` * Brand Voice: ${config.brandVoice.tone} / ${config.brandVoice.style}`);
  if (config.brandVoice.personality) {
    lines.push(` * Personality: ${config.brandVoice.personality}`);
  }
  lines.push(' */');
  lines.push('');

  // Start :root block
  lines.push(':root {');

  // Color properties
  lines.push('  /* Colors */');
  lines.push(`  --color-primary: ${config.colors.primary};`);
  lines.push(`  --color-secondary: ${config.colors.secondary};`);
  lines.push(`  --color-accent: ${config.colors.accent};`);
  lines.push(`  --color-background: ${config.colors.background};`);
  lines.push(`  --color-text: ${config.colors.text};`);
  lines.push('');

  // Derived color variables for UI states
  lines.push('  /* Derived Color States */');
  lines.push(`  --color-primary-hover: ${config.colors.primary};`);
  lines.push(`  --color-hover: ${config.colors.accent};`);
  lines.push('');

  // Gradient
  lines.push('  /* Gradients */');
  lines.push(`  --gradient-primary: linear-gradient(135deg, ${config.colors.primary} 0%, ${config.colors.secondary} 100%);`);
  lines.push('');

  // Typography
  lines.push('  /* Typography */');
  lines.push(`  --font-heading: ${config.typography.headingFont};`);
  lines.push(`  --font-body: ${config.typography.bodyFont};`);
  lines.push(`  --font-size-heading: ${config.typography.headingSize};`);
  lines.push(`  --font-size-body: ${config.typography.bodySize};`);
  lines.push(`  --line-height: ${config.typography.lineHeight};`);
  lines.push('');

  // Layout
  lines.push('  /* Layout */');
  lines.push(`  --spacing-unit: ${config.layout.spacingUnit};`);
  lines.push(`  --border-radius: ${config.layout.borderRadius};`);
  lines.push(`  --container-width: ${config.layout.containerWidth};`);

  // Close :root block
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
